<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectionRepository extends EntityRepository
{
    public function findLatest()
    {
        return $this->getEntityManager()
            ->getRepository('AppBundle:Connection')
            ->findOneBy([], ['id' => 'DESC']);

    }
}
