services:
#  http://stackoverflow.com/questions/17529657/how-to-use-properly-websockets-in-symfony2
#    chat:
#        class: AppBundle\Websocket\Chat
#        arguments: ['%chat.host%','%chat.port%']
